### ISSUE TITLE
Pusblish the latest version to Crates

### ISSUE THREAD

**Issue by ghost** [insanitybit/shannon-entropy#4]
I noticed that the latest version from the repository is not published to Crates.

Please publish it.

**Comment by insanitybit** [comment]
Master now reflects the latest version on crates.io, version 0.2.1.

**Comment by ghost** [comment]
This was fast. Thank you!

**Comment by insanitybit** [comment]
Happy to help - I've also gone ahead and published this crate as 1.0.0, as I think it is effectively in "maintenance mode" and I don't see myself making any breaking changes in the future.
