### ISSUE TITLE
Replace ln(2) variable with built-in constant.

### ISSUE THREAD

**Issue by svenvanhal** [insanitybit/shannon-entropy#5]
I've spotted a small improvement: the ln(2) value calculated [here](https://github.com/insanitybit/shannon-entropy/blob/8d4ec147b1a7da5161b8787770d9cdf27632dd6c/src/lib.rs#L51):

```rust
let log_div = (2.0 as f32).ln();
```

is also available as `std::f32::consts::LN_2`.

I do not know to what extent the compiler optimizes this away anyway, but using the built-in constant seems cleaner.

**Comment by insanitybit** [comment]
Thanks for the PR, I've merged it in.
